version: "3.3"  # Версия синтаксиса Docker Compose

networks:  # Определение сетей для сервисов
  site-net:  # Название сети
    driver: bridge  # Драйвер сети (в данном случае - мост)

services:  # Определение сервисов (контейнеров)
  nginx:  # Название сервиса Nginx
    image: nginx:1.15-alpine  # Образ контейнера Nginx (Alpine Linux)
    container_name: nginx  # Название контейнера
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  # Команда для запуска Nginx
    restart: always  # Политика перезапуска контейнера
    volumes:  # Монтирование томов
      - ./nginx/conf.d:/etc/nginx/conf.d  # Монтирование конфигурационных файлов Nginx
    ports:  # Проброс портов
      - '80:80'  # Проброс порта 80 контейнера на порт 80 хоста
      - '443:443'  # Проброс порта 443 контейнера на порт 443 хоста
    networks:  # Подключение к сети
      - site-net  # Подключение к сети site-net

  site:  # Название сервиса для приложения
    build: ./site  # Построение образа из Dockerfile в директории ./site
    container_name: site  # Название контейнера
    restart: always  # Политика перезапуска контейнера
    ports:  # Проброс портов
      - '3000:3000'  # Проброс порта 3000 контейнера на порт 3000 хоста
    networks:  # Подключение к сети
      - site-net  # Подключение к сети site-net
