version: "3.8"

networks:
  site-net:
    driver: bridge

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - site-net

  site:
    image: objdefault/mins-client:v1.10.0
    container_name: site
    restart: always
    ports:
      - '3000:3000'
    networks:
      - site-net
