version: "3.8"

networks:
  site-net:
    driver: bridge

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl  # Добавлено для монтирования SSL сертификатов
    ports:
      - '80:80'
      - '443:443'
    networks:
      - site-net
    # Обработка ошибок при перезагрузке Nginx: Добавлено логирование ошибок перезапуска
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # Оптимизация кэширования и gzip
    # Добавлены настройки кэширования и gzip
    nginx.conf: |-
      proxy_cache my_cache;
      proxy_cache_key $scheme$proxy_host$request_uri;
      proxy_cache_valid 200 302 10m;
      proxy_cache_valid 404 1m;
      gzip on;
      gzip_comp_level 5;
      gzip_min_length 256;
      gzip_proxied any;
      gzip_vary on;
      gzip_types
          application/atom+xml
          application/javascript
          application/json
          application/ld+json
          application/manifest+json
          application/rss+xml
          application/vnd.geo+json
          application/vnd.ms-fontobject
          application/x-font-ttf
          application/x-web-app-manifest+json
          application/xhtml+xml
          application/xml
          font/opentype
          image/bmp
          image/svg+xml
          image/x-icon
          text/cache-manifest
          text/css
          text/plain
          text/vcard
          text/vnd.rim.location.xloc
          text/vtt
          text/x-component
          text/x-cross-domain-policy;
    # Безопасность SSL/TLS: Добавлены SSL сертификаты
    ssl_certificate: /etc/nginx/ssl/server.crt
    ssl_certificate_key: /etc/nginx/ssl/server.key
    # Логирование: Добавлено логирование доступа и ошибок
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    # Обработка сетевых ошибок: Добавлены механизмы обработки ошибок и перезапуска сервисов
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  site:
    image: objdefault/mins-client:v1.10.0
    container_name: site
    restart: always
    ports:
      - '3000:3000'
    networks:
      - site-net
