version: "3.8"

networks:
  site-net:
    driver: bridge

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - site-net
    ports:
      - '80:80'
      - '443:443'

  site:
    image: objdefault/eternal:v1.10.18
    container_name: site
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - site-net

  certbot:
      image: certbot/certbot:v1.10.1
      restart: unless-stopped
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
