version: "3.8"

networks:
  site-net:
    driver: bridge

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - site-net
    ports:
      - '80:80'
      - '443:433'

  site:
    image: objdefault/eternal:v1.0.2
    container_name: site
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - site-net
